#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"
source "$PLUGIN_PATH/hipchat/hipchat_dokku_functions"



case "$1" in
  hipchat:settings)
    [[ -z $2 || -z $3 || -z $4 || -z $5 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";

    dokku_log_info1 "Creating HipChat config file for $APP...."

    HC_TOKEN="$3" HC_ROOM_ID="$4" HC_FROM="$5" HC_ENABLED="false" write_initial_config
    ;;

  hipchat:test)
    [[ -z $2 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";

    dokku_log_info1 "Sending a test mesage using $APP HipChat settings..."
    hipchat_message "test message from Dokku regarding $APP sent on $(date)"
    ;;

  hipchat:enable)
    [[ -z $2 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";

    dokku_log_info1 "Enabling HipChat for $APP..."
    enable_hipchat
    ;;

  hipchat:disable)
    [[ -z $2 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";

    dokku_log_info1 "Disabling HipChat for $APP..."
    disable_hipchat
    ;;

  hipchat:remove)
    [[ -z $2 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";

    dokku_log_info1 "Removing HipChat config for $APP..."
    remove_config
    ;;

  hipchat:info)
    [[ -z $2 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";

    dokku_log_info1 "Reading HipChat config file..."
    hipchat_info
    ;;

  hipchat:send_message)
    [[ -z $2 || -z $3 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";


    dokku_log_info1 "Sending HipChat message..."
    dokku_log_info2 "$3"
    hipchat_message "$3"
    ;;

  hipchat:set_hook)
    [[ -z $2 || -z $3 || -z $4 ]] && echo "Usage: $(show_help|grep "$1")" && exit 1
    verify_app_name "$2"
    APP="$2";
    CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";

    HOOK="$3"
    MSG="$4"

    HOOK="$HOOK" MSG="$MSG" set_hook
    ;;

  help)
    show_help
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac