#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"; CACHE_DIR="$DOKKU_ROOT/$APP/cache"
source "$(dirname $0)/../common/functions"
CONFIG="$DOKKU_ROOT/$APP/hipchat.conf";
source "$PLUGIN_PATH/hipchat/hipchat_dokku_functions"
[[ $(hipchat_is_enabled) == "false" ]] && dokku_log_info1 "HipChat: Notification isn't enabled for $APP." && exit 0
# config file exists, so we can do this at this point.
source $CONFIG

dokku_log_info1 "HipChat: hook-handler called for $0 $1 $2 $3"
HOOK=$(basename $0)

# TODO: Add configurable messages.
case "$HOOK" in 
	pre-deploy)
		handle_hook $HOOK
		;;

	check-deploy)
		handle_hook $HOOK
		;;

	post-deploy)
		handle_hook $HOOK
		;;

	pre-build)
		handle_hook $HOOK
		;;

	post-build)
		handle_hook $HOOK
		;;

	*)
		MSG="$0 $1 $2 $3 $4 $5"
		dokku hipchat:send_message $APP "$MSG"
		;;
esac
dokku_log_info1 "HipChat: hook-handler complete."
		
